version: '3'
services:
  grafana:
    container_name: grafana
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
